---
- hosts: all
  roles:
    - role: node_exporter
    - role: register_consul_service
      vars:
        service_name_prefix: node-exporter
        service_port: 9100
        service_tags: ["node-exporter","metrics"]
        http_path: /metrics
        interval: 30s
        timeout: 3s